### PR TITLE
Fix PHP error

### PR DESCRIPTION
**Pull request by phihuynh28**
PHP is throwing error "Attempted to load class "Files" from namespace "Files\Model". Did you forget a "use" statement" while trying to run the upload function

### CODE REVIEW

**Comment by rommelsantor** [comment]
@phihuynh28 Thank you for the pull request! Can you please provide more context around the issue you're experiencing?

There does not appear to be any non-namespaced reference to the `Files` class from within `lib/Model/File.php`, nor does the SDK define a function named `upload`.

**Comment by phihuynh28** [comment]
@rommelsantor Thanks for your response. So I'm using your SDK to upload files to the files.com server with this method `\Files\Model\File::uploadFile($remoteFile, $localFile);`
But I'm having an error in "File.php".

file_error

**Comment by rommelsantor** [comment]
@phihuynh28  Interesting. Thanks for the screenshot.

As this repository is just a mirror, we can't merge your PR here, but your fix is currently being merged in and deployed.

If you update the package in the next half hour or so, you should see that modification applied.

**Comment by phihuynh28** [comment]
Perfect, thanks @rommelsantor

**Comment by bombino** [comment]
This was merged via the mirror.  Thanks again.

**Pull request closed without merging**
